"""include email in user table

Revision ID: a3d34c17c7d6
Revises: 97725f2c71d3
Create Date: 2024-07-08 18:59:47.526203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a3d34c17c7d6"
down_revision: Union[str, None] = "97725f2c71d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email")
    # ### end Alembic commands ###
